---

- name: Copy Spark Master service script
  template:
    src: spark-master-service.j2
    dest: "{{ systemd_services_dir }}/spark-master.service"

- name: Copy Spark History Server service script
  template:
    src: spark-historyserver-service.j2
    dest: "{{ systemd_services_dir }}/spark-historyserver.service"

- name: Copy Spark Slave service script
  template:
    src: spark-slaves-service.j2
    dest: "{{ systemd_services_dir }}/spark-slaves.service"

- name: Copy Spark Master Monit service
  template:
    src: monit-spark-master.j2
    dest: /etc/monit.d/service-spark-master
  when: setup_monit

- name: Copy Spark History Server Monit service
  template:
    src: monit-spark-history.j2
    dest: /etc/monit.d/service-spark-history
  when: setup_monit

- name: Copy Spark slave Monit service
  template:
    src: monit-spark-slave.j2
    dest: /etc/monit.d/service-spark-slave
  when: setup_monit

- name: Start Spark Master service
  service:
    name: spark-master
    state: started

- name: Start Spark History Server service
  service:
    name: spark-historyserver
    state: started

- name: Start Spark Slaves service
  service:
    name: spark-slaves
    state: started

- name: Enable Spark Master service
  service:
    name: spark-master
    enabled: yes 
  when: setup_monit

- name: Enable Spark History Server service
  service:
    name: spark-historyserver
    enabled: yes 
  when: not setup_monit

- name: Enable Spark Slaves service
  service:
    name: spark-slaves
    enabled: yes 
  when: not setup_monit
