---
redis_config_path: /etc/redis
redis_conf_file: "{{ redis_config_path }}/{{ redis_conf_file_name }}"
redis_packages:
  - redis-server
redis_daemon: redis-server
redis_pid: "{{ redis_pid_path }}/{{redis_daemon}}.pid"
