---

- name: Copy redis service script
  template:
    src: redis-service.j2
    dest: "{{ systemd_services_dir }}/{{ redis_daemon }}.service"

- name: Start redis service
  service:
    name: "{{ redis_daemon }}"
    state: restarted
  

- name: Enable redis service
  service:
    name: "{{ redis_daemon }}"
    enabled: yes 
